on:
  push:
    tags:
    - 'v*'

jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - uses: erlef/setup-beam@v1
        with:
          otp-version: '24.3'
          rebar3-version: '3.14.3'
        run: |
          rebar3 as prod release
          tar jcf orc-${GITHUB_REF_NAME#v}-ubuntu-bionic-x86_64.tar.bz2 -C _build/prod/rel/ orc
          md5sum orc-${GITHUB_REF_NAME#v}-ubuntu-bionic-x86_64.tar.bz2 | cut -f1 -d ' ' > orc-${GITHUB_REF_NAME#v}-ubuntu-bionic-x86_64.md5sum

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files:
            - orc-${GITHUB_REF_NAME#v}-ubuntu-bionic-x86_64.tar.bz2
            - orc-${GITHUB_REF_NAME#v}-ubuntu-bionic-x86_64.md5sum
