on:
  push:
    tags:
      - 'v*'
    branch:
      - ga

jobs:
  ubuntu22-amd64:
    runs-on: self-hosted
    env:
      ImageOS: ubuntu22
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '24'
          rebar3-version: '3.16.1'
      - run: |
          rebar3 as prod release
          strip _build/prod/rel/orc/erts-*/bin/* || true
          tar jcf orc-${GITHUB_REF_NAME#v}-ubuntu-jammy-x86_64.tar.bz2 -C _build/prod/rel/ orc
          md5sum orc-${GITHUB_REF_NAME#v}-ubuntu-jammy-x86_64.tar.bz2 | cut -f1 -d ' ' > orc-${GITHUB_REF_NAME#v}-ubuntu-jammy-x86_64.md5sum

  ubuntu20-amd64:
    runs-on: self-hosted
    env:
      ImageOS: ubuntu20
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '24'
          rebar3-version: '3.16.1'
      - run: |
          rebar3 as prod release
          strip _build/prod/rel/orc/erts-*/bin/* || true
          tar jcf orc-${GITHUB_REF_NAME#v}-ubuntu-focal-x86_64.tar.bz2 -C _build/prod/rel/ orc
          md5sum orc-${GITHUB_REF_NAME#v}-ubuntu-focal-x86_64.tar.bz2 | cut -f1 -d ' ' > orc-${GITHUB_REF_NAME#v}-ubuntu-focal-x86_64.md5sum

  release:
    runs-on: self-hosted
    needs: ['ubuntu22-amd64', 'ubuntu20-amd64']
    steps:
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            orc-*
